#!/bin/bash

sudo ./system_backup.sh

sudo cp ./usr/tft35a-overlay.dtb /boot/overlays/
sudo cp ./usr/tft35a-overlay.dtb /boot/overlays/tft35a.dtbo
root_dev=`grep -oPr "root=[^\s]*" /boot/cmdline.txt | awk -F= '{printf $NF}'`

sudo cp -rf /boot/config.txt ./boot/config.txt.bak
sudo echo "#LCD35 Config" >> ./boot/config.txt.bak
sudo echo "hdmi_force_hotplug=1" >> ./boot/config.txt.bak

sudo echo "dtparam=i2c_arm=on" >> ./boot/config.txt.bak
sudo echo "dtparam=spi=on" >> ./boot/config.txt.bak
sudo echo "enable_uart=1" >> ./boot/config.txt.bak
sudo echo "dtoverlay=tft35a:rotate=90" >> ./boot/config.txt.bak
sudo cp -rf ./boot/config.txt.bak /boot/config.txt

sudo cp ./usr/cmdline.txt /boot/

sudo cp ./usr/inittab /etc/

sudo touch ./.have_installed
echo "gpio:resistance:35:90:480:320" > ./.have_installed

sudo sync
sudo sync
sleep 1

echo "reboot now"
sudo reboot
